### PR TITLE
Switch to map

### PR DESCRIPTION
**Pull request by MalteMagnussen**
Made a switch into an object literal

https://ultimatecourses.com/blog/deprecating-the-switch-statement-for-object-literals

### CODE REVIEW

**Review by Runi-VN — APPROVED** [review]
I read up on this last night when you suggested it.

There are some points brought up for/against it in the two links below that I think  we should all know:

https://stackoverflow.com/questions/13383798/using-object-literal-rather-than-switch-statement
https://spin.atomicobject.com/2016/11/06/switch-statements-object-literals/

As far as I'm aware, object literals cannot _chain_ or _combine_ like a switch can:
```js
 switch (file.extension) {
        case "txt": //both cases return "document.jpg"
        case "doc":
            return "document.jpg";
        ...
```

It seems that object literals are good performance wise (usually), and readability is fine for shorter cases, so I agree on the usage here :) Cool concept.

**Comment by MalteMagnussen** [comment]
image

**Comment by MalteMagnussen** [comment]
image

**Comment by MalteMagnussen** [comment]
Just a fun little side-thing to do. 
I was posting in r/learnprogramming and bantering, and showed the switch, and whined about how I'm an idiot that forgot "break;" and people commented that I should just use an Object instead, like this.

**Pull request merged**
