### PR TITLE
Navigation fix and small styling fix

### LINKED ISSUE #42: Fix buttons in app and add navigation
Make sure correct components and constants are used.
And see if it's possible to implement real navigation instead of the if/switch thing the german taught us.

### PR DESCRIPTION
**Pull request by Castau**
* [x] Removed HomeScreen
* [x] Fixed styling for CreateUserScreen and LoginScreen (and LoginCard)
* [x] Added navigation instead of if/switch in app.js. 

How **NAVIGATION** works:
In App.js (**and only here**)
image
I've added the navigation components. 

How to use
First, in App.js add a Stack.Screen component for the Screen you want navigation for
```javascript
<Stack.Screen name="TestScreen">{props => <TestScreen {...props} testState={someTestState}/>}</Stack.Screen>
<Stack.Screen name="OtherScreen">{props => <OtherScreen{...props} />}</Stack.Screen>
```
*I'am a little unsure about what the props actually does, since state is passed on as shown above.*   
Then, in the Screen you just added above and want to navigate out of (in a button fx)
```javascript
const TestScreen= props => {
  // code
    return (
      <Card style={styles.container}>
          <View style={styles.button}>
            <Button color={colors.grey} title=TEST" 
               onPress={() => props.navigation.navigate('OtherScreen')}
             />
          </View>
      </Card >
  );
};
```
The **navigation** prop can be deconstructed as normal if you prefer that.
```
const TestScreen= ({ navigation, testState }) => { ....
```
The navigation methods we will use are:
- `navigation.navigate('OtherScreen')`
  - navigates to the specified screen
- `navigation.goBack()`
  - navigates back to the previous screen

**[REACT DOCUMENTATION](https://reactnative.dev/docs/navigation)**

---

The fixed styles look like this now:
**LoginScreen**
image

**CreateUserScreen**
image

In those files I've changed the buttonstyle to the following:
```javascript
button: {
        width: 110,
        marginVertical: 10
    },
```

If you are unsure how to style a button, this is an example (and yes the button **has** to be in a view, the button itself cannot be styled beyond the color):
```javascript
<View style={styles.button}>
    <Button color={colors.secondary} title="TAKE ME BACK"/>
</View>
```

### CODE REVIEW

**Review by MalteMagnussen — APPROVED** [review]
Looks great. Nice with easy navigation.

**Comment by MalteMagnussen** [comment]
In this example, they use self-closing tags. Any particular reason you used the other way? https://reactnative.dev/docs/navigation#usage
image

Ahh, I found it! 
image

So to pass along `signedIn` and `setSignedIn` we need this format
image

**Comment by Castau** [comment]
> In this example, they use self-closing tags. Any particular reason you used the other way? 

Yes, as you found out, in order to pass along state you need both the open and closing tag :)

**Review by Runi-VN — APPROVED** [review]
There's quite a lot of changes in the package.json file. I assume they are all needed?

Nice PR and walkthrough, I will try to integrate it into mapscreen.

**Comment by Castau** [comment]
> There's quite a lot of changes in the package.json file. I assume they are all needed?
> 
> Nice PR and walkthrough, I will try to integrate it into mapscreen.

Yes they are all needed and remember to `npm install` :D

**Pull request merged**
